export const communityQuotes = [
  "coding is a superpower",
  "build with passion",
  "ship it today",
  "debug your dreams",
  "Kerala codes better",
  "community over competition",
  "learn in public",
  "side projects matter",
  "don't fly solo",
  "be kind always",
  "skills pay the bills",
  "commit and push",
  "break things beautifully",
  "iterate and improve",
  "start before ready",
  "fail fast learn faster",
  "code creates impact",
  "think global build local",
  "teach what you learn",
  "collaborate and conquer",
];